### ISSUE TITLE
Add an Edit Button on the Home Page

### ISSUE THREAD

**Issue by Industry4** [Industry4/MultiPlug.Ext.FileImporter#1]
- Set issue status to **In Progress**, over there -->

- Edit File **Home.cshtml** at location: `MultiPlug.Ext.FileImporter\src\MultiPlug.Ext.FileImporter\Controllers\Settings\Home\Home.cshtml`

### From:
```
<td class="span1">
    <a class="btn btn-red btn-deletefile" href="@Raw(Model.Context.Paths.Home)file/delete/?id=@Model.Extension.Model.Guid[i]">
        <i class="icon-trash"></i>
    </a>
</td>
```

### To:

```
<td class="span2">
    <div class="btn-group">
        <a class="btn btn-blue" href="@Raw(Model.Context.Paths.Home)file/?id=@Model.Extension.Model.Guid[i]">
            <i class="icon-edit"></i>
        </a>
        <a class="btn btn-red btn-deletefile" href="@Raw(Model.Context.Paths.Home)file/delete/?id=@Model.Extension.Model.Guid[i]">
            <i class="icon-trash"></i>
        </a>
    </div>
</td>
```

**Note:** spanXX must always equal 12, so you must also alter the **th** and **td** values as the span has been changed from 1 (in the From example `span1`) to 2 (in the To example `span2`). Span is the width size.

- Compile the .dll and Test your change.
- Get your code change Code Reviewed by your supervisor.

### Commit Message
Use the Commit Message of this issue: `#1` and github will link the code change to this issue.

- Set issue status to **Done**, over there -->
- Close the issue below, stating any helpful notes in the comment for the end user.

**Comment by JBJ05** [comment]
Button Added.

**Comment by Industry4** [comment]
### User Interface
![image](https://github.com/Industry4/MultiPlug.Ext.FileImporter/assets/14904422/8c192d3f-03b2-4a7b-86e7-12b3aa6d3d92)
