### ISSUE TITLE
Add a About Page

### ISSUE THREAD

**Issue by Industry4** [Industry4/MultiPlug.Ext.FileImporter#2]
Using the code: `var ExecutingAssembly = System.Reflection.Assembly.GetExecutingAssembly();`

Display the following attributes of the .dll :

- Version
- Title (this will be the Extension)
- Description
- Company (this will be Maintainer) and apply a hyperlink
- Product
- Copyright
- Trademark

Using the example code:
` string Title = ExecutingAssembly.GetCustomAttribute<AssemblyTitleAttribute>`

The C Sharp Razor example (.cshtml) to dynamically write this out would be:
`@Raw(Model.Extension.Model.Version)`

Navigation Bars
2 Navigation Bars need to be created for the About Page and the File Page. The following shows you how to re-use html using Razor `@Include( ) `

- Create a .cshtml file in a folder called SharedRazor - Call it something appropriate to the Navigation Bar. Use the Example  Template below: 
```
@model MultiPlug.Base.Http.EdgeApp
@functions {
    public string NavLocationIsHome()
    {
        return Model.Context.Paths.Current == Model.Context.Paths.Home ? "active" : string.Empty;
    }

    public string NavLocationIsAbout()
    {
        return Model.Context.Paths.Current == Model.Context.Paths.Home + "about/" ? "active" : string.Empty;
    }
}

<div class="row-fluid">
    <ul class="nav nav-tabs">
        <li class="@NavLocationIsHome()"><a href="@Raw(Model.Context.Paths.Home)">Home</a></li>
        <li class="@NavLocationIsAbout()"><a href="@Raw(Model.Context.Paths.Home)about/">About</a></li>
        }
    </ul>
</div>
```

- Add this to the .dll resources, as you did when you created the About.cshtml file.
- Create a Template ID in Templates.cs, as you did when you created the About.cshtml file.

You can create conditional html areas by using the following example:
```
@if ( ! string.IsNullOrEmpty(Model.Extension.Model.Guid) )
{
<li class=""><a href="">Lane</a></li>
}
```
- Now you can include the Template in the Home.cshtml and About.cshtml pages by using the following example:

`@Include("MultiPlug.Ext.FileImporter.WHAT-EVER-YOU-CALLED-THE-TEMPLATE-ID-ABOVE")`

- Now do the same for File.cshtml - You can do the same, or copy the Navigation Bar html directly into File.cshtml without referencing a new shared navigation bar template.

**Comment by JBJ05** [comment]
About Page

**Comment by Industry4** [comment]
### User Interface
![image](https://github.com/Industry4/MultiPlug.Ext.FileImporter/assets/14904422/57549c9d-e54a-46e5-b2fb-7ad48423a943)
