### ISSUE TITLE
Allow Edit of File Type Description

### ISSUE THREAD

**Issue by Industry4** [Industry4/MultiPlug.Ext.FileImporter#3]
**Displaying the Current Value**
- Within  `<div class="box non-collapsible"></div>` add a new `<input>` using the following example:
```
<h4>File Properties</h4>
<div class="row-fluid">
    <div class="well">
        <div class="row-fluid">
            <input type="hidden" name="Guid" value="@Model.Extension.Model.Guid">
            <input type="text" name="" class="span3" placeholder="File Type Description" value="">
        </div>
    </div>
</div>
```

- Change the value of `name=""` to something appropriate.
- Change the `Get()` of FileController.cs to the Data Model contains the current value of the FileTypeDescription known in code as `Type`.
- Change the value of `value=""` so the value is the current value, use what you learnt in #2

**Saving The New Value**
- In FileController.cs create a `Post()` function with a single parameter of a Data Model (class) containing the string properties 1. Guid and 2. the name you used for `name=""`
- the `Post()` function should search for the correct `FileImporterComponent` using the Guid (use the same code as the `Get()`) then call the `UpdateProperties(FileImporterProperties theNewProperties)` function to perform the update.
- Finally Return `return new Response` using the same code found in the `Get()`

**Comment by JBJ05** [comment]
Change File Type Description

**Comment by Industry4** [comment]
### User Interface
![image](https://github.com/Industry4/MultiPlug.Ext.FileImporter/assets/14904422/265d82bd-dc3b-4c3b-9d96-d3b6eb51ed0e)
